version: '3'

services:

  music-library-db:
    container_name: music-library-db
    image: postgres:13
    environment:
      POSTGRES_DB: ${MUSIC_LIBRARY_MS_DATABASE_NAME}
      POSTGRES_USER: ${MUSIC_LIBRARY_MS_DATABASE_USER}
      POSTGRES_PASSWORD: ${MUSIC_LIBRARY_MS_DATABASE_PASS}
    ports:
      - ${MUSIC_LIBRARY_MS_DATABASE_PORT}:5432
    networks:
      - microservices-architecture

  player-db:
    container_name: player-db
    image: postgres:13
    environment:
      POSTGRES_DB: ${PLAYER_MS_DATABASE_NAME}
      POSTGRES_USER: ${PLAYER_MS_DATABASE_USER}
      POSTGRES_PASSWORD: ${PLAYER_MS_DATABASE_PASS}
    ports:
      - ${PLAYER_MS_DATABASE_PORT}:5432
    networks:
      - microservices-architecture

  accounts-db:
    container_name: accounts-db
    image: postgres:13
    environment:
      POSTGRES_DB: ${ACCOUNTS_MS_DATABASE_NAME}
      POSTGRES_USER: ${ACCOUNTS_MS_DATABASE_USER}
      POSTGRES_PASSWORD: ${ACCOUNTS_MS_DATABASE_PASS}
    ports:
      - ${ACCOUNTS_MS_DATABASE_PORT}:5432
    networks:
      - microservices-architecture

  spotify-monolith-db:
    container_name: spotify-monolith-db
    image: postgres:13
    environment:
      POSTGRES_DB: ${SPOTIFY_MONOLITH_DATABASE_NAME}
      POSTGRES_USER: ${SPOTIFY_MONOLITH_DATABASE_USER}
      POSTGRES_PASSWORD: ${SPOTIFY_MONOLITH_DATABASE_PASS}
    ports:
      - ${SPOTIFY_MONOLITH_DATABASE_PORT}:5432
    networks:
      - microservices-architecture

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
        - 5672:5672
        - 15672:15672
    environment:
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}

    networks:
      - microservices-architecture

networks:
  microservices-architecture:
    driver: bridge

volumes:
  pgadmin_root_prefs:
    driver: local
  postgresql_data:
    driver: local
  postgresql_bin:
    driver: local