version: '3'

services:
  music-library-db:
    container_name: music-library-db
    image: postgres:13
    environment:
      POSTGRES_DB: music-library
      POSTGRES_USER: music-library
      POSTGRES_PASSWORD: music-library
    volumes:
      - postgresql_bin:/usr/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - microservices-architecture

networks:
  microservices-architecture:
    driver: bridge

volumes:
  pgadmin_root_prefs:
    driver: local
  postgresql_data:
    driver: local
  postgresql_bin:
    driver: local